Be significantly smarter about builds and installs

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -5,32 +5,36 @@ install:
     - mkdir -p vendor
     - pushd vendor
     - |
-        if [ ! -f /usr/local/lib/liblept.so.5.0.1 ] || (git log -n1 | grep -q redo-lep); then
+        if [ ! -d leptonica-1.74.4 ] || (git log -n1 | grep -q redo-lep); then
             curl -Lo leptonica.tar.gz https://github.com/DanBloomberg/leptonica/archive/1.74.4.tar.gz
             tar xzf leptonica.tar.gz
-            cd leptonica-1.74.4
-            mkdir -p $HOME/local
+        fi
+    - cd leptonica-1.74.4
+    - |
+        if [ ! -f src/.libs/liblept.so.5.0.1 ] || (git log -n1 | grep -q redo-lep); then
             autoreconf --install
             ./configure
             make -j
-            sudo make install
-            cd ..
         fi
+    - sudo make install
+    - cd ..
     - |
-        if [ ! -f /usr/local/bin/tesseract ] || (git log -n1 | grep -q redo-tess); then
+        if [ ! -d tesseract-3.05.01 ] || (git log -n1 | grep -q redo-tess); then
             curl -Lo tesseract.tar.gz https://github.com/tesseract-ocr/tesseract/archive/3.05.01.tar.gz
             tar xzf tesseract.tar.gz
-            cd tesseract-3.05.01
+        fi
+    - cd tesseract-3.05.01
+    - |
+        if [ ! -f /usr/local/bin/tesseract ] || (git log -n1 | grep -q redo-tess); then
             echo 'tesseract_LDADD += $(LEPTONICA_LIBS)' >> api/Makefile.am
             ./autogen.sh
             ./configure
             make -j
-            sudo make install
-            sudo ldconfig
-            which tesseract || echo "Can't find tesseract in PATH"
         fi
-    - mkdir -p $HOME/tessdata
-    - cd $HOME/tessdata
+    - sudo make install
+    - sudo ldconfig
+    - which tesseract || echo "Can't find tesseract in PATH"
+    - cd /usr/local/share/tessdata
     - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.traineddata
     - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.tesseract_cube.nn
     - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.word-freq
@@ -56,7 +60,6 @@ cache:
     directories:
         - vendor
         - $HOME/.cache/pip
-        - $HOME/tessdata
 addons:
     apt:
         packages:
