Fix Travis config (#1)
* Actually install Tox on Travis

* Properly configure Tesseract

* Quit using tox to manage tests

* Compile a recent Tesseract manually on Travis

Because "yeah, distros never update anything, here's some prebuilt Linux
binaries for you!" would be too hard.

* Follow curl redirects, and only run on 3.5 for now

* Potentially autotool the crap out of leptonica

This might be the first time I've tried to use a software package that
didn't give me a ./configure script.

* Maybe autotools heard me whining and broke Travis

* Maybe I should be using my Linux VM for this

* Apparently the VM was overkill

* Don't run more commands than needed

Apparently "just run everything" was a common enough use case that the
`autoreconf` command already does that. Who knew?

* Fine, you can run as root

* Cache things

* Use a more recent Leptonica version

* Do a bunch of smarter things

* Manually link against leptonica???

I don't know if this will do this, or if this is why nothing works, but
I no longer know anything.

* Hopefully, skip compilation if it's unnecessary

* Wind up in the right place after compiling tesseract

* Why can't anything be simple or intuitive?

* Potentially improve lep/tess handling

This means I have to say things in the actual commit log
if I want to rebuild things on Travis, but I'm OK with that.

* Apparently you need this

* Be significantly smarter about builds and installs

* Fix a permissions thing

* Look in the right place for compiled Tesseract

* Pretend to compile tesseract if not actually compiling

Apparently tesseract doesn't stay compiled so `sudo make install` was
recompiling it. That's not a good thing.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,2 +1,78 @@
 language: python
-script: tox
+sudo: required
+install:
+    - pip install -r requirements.txt
+    - mkdir -p vendor
+    - pushd vendor
+    - |
+        if [ ! -d leptonica-1.74.4 ] || (git log -n1 | grep -q redo-lep); then
+            curl -Lo leptonica.tar.gz https://github.com/DanBloomberg/leptonica/archive/1.74.4.tar.gz
+            tar xzf leptonica.tar.gz
+        fi
+    - cd leptonica-1.74.4
+    - |
+        if [ ! -f src/.libs/liblept.so.5.0.1 ] || (git log -n1 | grep -q redo-lep); then
+            autoreconf --install
+            ./configure
+            make -j
+        fi
+    - sudo make install
+    - cd ..
+    - |
+        if [ ! -d tesseract-3.05.01 ] || (git log -n1 | grep -q redo-tess); then
+            curl -Lo tesseract.tar.gz https://github.com/tesseract-ocr/tesseract/archive/3.05.01.tar.gz
+            tar xzf tesseract.tar.gz
+        fi
+    - cd tesseract-3.05.01
+    - |
+        if [ ! -f api/.libs/tesseract ] || (git log -n1 | grep -q redo-tess); then
+            echo 'tesseract_LDADD += $(LEPTONICA_LIBS)' >> api/Makefile.am
+            ./autogen.sh
+            ./configure
+            make -j
+        else
+            make -t
+        fi
+    - sudo make install
+    - sudo chmod a+rwx /usr/local/share/tessdata
+    - sudo ldconfig
+    - which tesseract || echo "Can't find tesseract in PATH"
+    - cd /usr/local/share/tessdata
+    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.traineddata
+    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.tesseract_cube.nn
+    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.word-freq
+    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.size
+    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.params
+    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.nn
+    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.lm
+    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.fold
+    - curl -LO https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.cube.bigrams
+    - popd
+script: pytest -vv
+python:
+    # - "2.7"
+    # - "3.2"
+    # - "3.3"
+    # - "3.4"
+    - "3.5"
+    # - "3.6"
+    # - "nightly"
+    # - "pypy"
+    # - "pypy3"
+cache:
+    directories:
+        - vendor
+        - $HOME/.cache/pip
+addons:
+    apt:
+        packages:
+            - g++
+            - autoconf
+            - automake
+            - libtool
+            - autoconf-archive
+            - pkg-config
+            - libpng12-dev
+            - libjpeg8-dev
+            - libtiff5-dev
+            - zlib1g-dev
